using System;
using System.Reflection;

[assembly: AssemblyTitle("Nibble")]
[assembly: AssemblyDescription("Battery tray and settings for the Royal Kludge M3 mouse")]
[assembly: AssemblyProduct("Nibble")]
[assembly: AssemblyCompany("shanuflash")]
[assembly: AssemblyCopyright("Copyright (c) shanuflash")]
// AssemblyVersion is generated by build.cmd from NIBBLE_VERSION.

namespace Nibble
{
    static class AppInfo
    {
        public const string Name = "Nibble";
        public const string Repo = "shanuflash/nibble";
        public const string ReleasesPage = "https://github.com/" + Repo + "/releases";

        public static Version Version
        {
            get
            {
                var v = Assembly.GetExecutingAssembly().GetName().Version;
                return new Version(v.Major, v.Minor, Math.Max(0, v.Build));
            }
        }
    }
}
