using System;
using System.Drawing;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;

[assembly: AssemblyTitle("Nibble")]
[assembly: AssemblyDescription("Battery tray for the Royal Kludge M3 mouse")]
[assembly: AssemblyProduct("Nibble")]
// AssemblyVersion is generated by build.cmd from NIBBLE_VERSION.

namespace Nibble
{
    static class Program
    {
        [DllImport("user32.dll")] static extern bool SetProcessDPIAware();

        // Cycles the DPI popup through three stages, like pressing the DPI button, then exits.
        static void TestDpiHud()
        {
            SetProcessDPIAware();
            Application.EnableVisualStyles();
            int[] dpis = { 800, 1600, 3200 };
            Color[] leds = { Theme.Hex(0xFF0000), Theme.Hex(0x00FF00), Theme.Hex(0x00FFFF) };
            int i = 0;
            var t = new System.Windows.Forms.Timer { Interval = 400 };
            t.Tick += delegate
            {
                t.Interval = 900;
                if (i < 3) { DpiHud.Show(dpis[i], i + 1, 3, leds[i]); i++; }
                else if (i++ > 6) { t.Stop(); Application.ExitThread(); }
            };
            t.Start();
            Application.Run();
        }

        // Shows each real alert a few seconds apart, then exits.
        static void TestNotifications()
        {
            SetProcessDPIAware();
            Application.EnableVisualStyles();
            var steps = new Action[]
            {
                delegate { TrayApp.ShowLowAlert(18, null, true); },
                delegate { TrayApp.ShowFullAlert(null, true); },
                delegate { Application.ExitThread(); }
            };
            int i = 0;
            var t = new System.Windows.Forms.Timer { Interval = 500 };
            t.Tick += delegate { t.Interval = 7500; steps[i++](); if (i == steps.Length) t.Stop(); };
            t.Start();
            Application.Run();
        }

        [STAThread]
        static void Main(string[] args)
        {
            if (args.Length == 2 && args[0] == "--make-icon")
            {
                IconArt.WriteIco(args[1]);
                return;
            }

            if (args.Length >= 3 && args[0] == "--snapshot")
            {
                SetProcessDPIAware();
                int pct = args.Length > 3 ? int.Parse(args[3]) : 57;
                bool chg = args.Length > 4 && args[4] == "charging";
                bool on = !(args.Length > 4 && args[4] == "asleep");
                new TrayApp(args[1], args[2] == "dark", pct, chg, on, Array.IndexOf(args, "settings") >= 0);
                return;
            }

            if (args.Length >= 4 && args[0] == "--snapshot-settings")
            {
                SetProcessDPIAware();
                TrayApp.SnapshotCharging = Array.IndexOf(args, "charging") >= 0;
                int side; if (args.Length >= 5 && int.TryParse(args[4], out side)) SettingsWindow.SideStyle = side;
                new TrayApp(args[1], args[2] == "dark", int.Parse(args[3]));
                return;
            }

            if (args.Length >= 1 && args[0] == "--test-dpi-hud")
            {
                TestDpiHud();
                return;
            }

            if (args.Length >= 1 && args[0] == "--test-notifications")
            {
                TestNotifications();
                return;
            }

            bool created;
            using (var mutex = new Mutex(true, @"Local\Nibble.RK-M3", out created))
            {
                if (!created) return;
                SetProcessDPIAware();
                Application.EnableVisualStyles();
                Application.SetCompatibleTextRenderingDefault(false);
                bool show = Array.IndexOf(args, "--show") >= 0;
                var ctx = new TrayApp(show);
                if (Array.IndexOf(args, "--settings") >= 0) { var t = new System.Windows.Forms.Timer { Interval = 1500 }; t.Tick += delegate { t.Stop(); ctx.OpenSettings(); }; t.Start(); }
                Application.Run(ctx);
            }
        }
    }
}
